### ISSUE TITLE
“Buy Farm Fresh now” button doesn’t work. 

### ISSUE THREAD

**Issue by kulakajak** [producerun/produceruncatarse#74]

**Comment by kulakajak** [comment]
Originally was explore_path, I do not know why Vivek changed to signup.
Do you want to be different path for logged in and logged out users ?

**Comment by hackandgrow** [comment]
I did say originally to have it as farmer sign up but the text didn't get changed.

Please have it as explore path on the homepage for buyers.

Thanks Dusan

**Comment by kulakajak** [comment]
I think this is working now.
